version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: sophub-postgres
    environment:
      POSTGRES_USER: sophub
      POSTGRES_PASSWORD: sophub
      POSTGRES_DB: sophub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sophub-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  pgdata:


