"""add sop_allowed_teams and user_teams v2

Revision ID: 6b4dd8afec17
Revises: 91303c32ba0a
Create Date: 2025-09-23 05:47:26.948409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4dd8afec17'
down_revision: Union[str, Sequence[str], None] = '91303c32ba0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sop_allowed_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sop_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sop_id', 'team_id', name='uq_sop_allowed_team')
    )
    op.create_index(op.f('ix_sop_allowed_teams_sop_id'), 'sop_allowed_teams', ['sop_id'], unique=False)
    op.create_index(op.f('ix_sop_allowed_teams_team_id'), 'sop_allowed_teams', ['team_id'], unique=False)
    op.create_table('user_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_user_team')
    )
    op.create_index(op.f('ix_user_teams_team_id'), 'user_teams', ['team_id'], unique=False)
    op.create_index(op.f('ix_user_teams_user_id'), 'user_teams', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_teams_user_id'), table_name='user_teams')
    op.drop_index(op.f('ix_user_teams_team_id'), table_name='user_teams')
    op.drop_table('user_teams')
    op.drop_index(op.f('ix_sop_allowed_teams_team_id'), table_name='sop_allowed_teams')
    op.drop_index(op.f('ix_sop_allowed_teams_sop_id'), table_name='sop_allowed_teams')
    op.drop_table('sop_allowed_teams')
    # ### end Alembic commands ###
