"""sop_allowed_teams and user_teams

Revision ID: 91303c32ba0a
Revises: ebeec906120e
Create Date: 2025-09-23 05:38:39.515729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91303c32ba0a'
down_revision: Union[str, Sequence[str], None] = 'ebeec906120e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
