"""create sops table

Revision ID: bfd11fc63598
Revises: d36d08d879f7
Create Date: 2025-09-22 08:56:46.774693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfd11fc63598'
down_revision: Union[str, Sequence[str], None] = 'd36d08d879f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sop_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sops_department'), 'sops', ['department'], unique=False)
    op.create_index(op.f('ix_sops_id'), 'sops', ['id'], unique=False)
    op.create_index(op.f('ix_sops_sop_id'), 'sops', ['sop_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sops_sop_id'), table_name='sops')
    op.drop_index(op.f('ix_sops_id'), table_name='sops')
    op.drop_index(op.f('ix_sops_department'), table_name='sops')
    op.drop_table('sops')
    # ### end Alembic commands ###
